const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp();
const profiles = require("./api/profile");
const customer = require("./api/customers");
const employee = require("./api/employees");
const service = require("./admin/services");
const plan = require("./admin/plans");
const shop = require("./admin/shops");
const dashboard = require("./admin/dashboard");
const user = require("./api/users");
const gallery = require("./admin/gallery");

exports.users = functions.https.onRequest(user);
exports.profile = functions.https.onRequest(profiles);
exports.customers = functions.https.onRequest(customer);
exports.employees = functions.https.onRequest(employee);
exports.services = functions.https.onRequest(service);
exports.plans = functions.https.onRequest(plan);
exports.dashboards = functions.https.onRequest(dashboard);
exports.shops = functions.https.onRequest(shop);
exports.gallery = functions.https.onRequest(gallery);
